from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship
from sqlalchemy import String, ForeignKey, Numeric, DateTime
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any
from enum import Enum
from sqlalchemy.dialects.postgresql import JSONB
from pgvector.sqlalchemy import VECTOR


class DocumentStatus(Enum):
    PROCESSING = "processing" ## under injestion and not ready to be used by the llms(like still doing the embeddings, etc)
    ACTIVE = "active" ## Ready to be used by the llms
    ARCHIVED = "archived" ## No longer used by the llms(its an old version), only to keep history of the document
    
class Base(DeclarativeBase):
    pass


# These are the internal employees who will actually use opspilot
class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(255))
    email: Mapped[str] = mapped_column(String(255), unique=True, index=True)
    role: Mapped[str] = mapped_column(String(100))

    cases: Mapped[list["Case"]] = relationship(back_populates="assigned_user")

    def __repr__(self) -> str:
        return f"User(id={self.id!r}, name={self.name!r}, email={self.email!r}, role={self.role!r})"


# these are the customers of the company that will use opspilot
# We are creating them for testing purposes
class Customer(Base):
    __tablename__ = "customers"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(255))
    email: Mapped[str] = mapped_column(String(255), unique=True, index=True)
    country: Mapped[str] = mapped_column(String(100))

    orders: Mapped[list["Order"]] = relationship(back_populates="customer")
    payments: Mapped[list["Payment"]] = relationship(back_populates="customer")

    def __repr__(self) -> str:
        return f"Customer(id={self.id!r}, name={self.name!r}, email={self.email!r}, country={self.country!r})"


## Orders for our company


class Order(Base):
    __tablename__ = "orders"

    id: Mapped[int] = mapped_column(primary_key=True)
    order_id: Mapped[str] = mapped_column(
        String(100), unique=True, index=True
    )  # order-tag generated by the backend
    customer_id: Mapped[int] = mapped_column(ForeignKey("customers.id"), index=True)
    total: Mapped[Decimal] = mapped_column(Numeric(12, 2))
    status: Mapped[str] = mapped_column(String(50))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    ## Relationships with the order
    customer: Mapped["Customer"] = relationship(back_populates="orders")
    payments: Mapped[list["Payment"]] = relationship(back_populates="order")
    returns: Mapped[list["Return"]] = relationship(back_populates="order")
    refunds: Mapped[list["Refund"]] = relationship(back_populates="order")
    status_history: Mapped[list["OrderStatusHistory"]] = relationship(
        back_populates="order"
    )
    items: Mapped["OrderItem"] = relationship(back_populates="order")

    def __repr__(self) -> str:
        return f"Order(id={self.id!r}, order={self.order_id!r}, customer={self.customer_id!r}, total={self.total!r}, status={self.status!r}, created-at={self.created_at!r}, updated-at={self.updated_at!r})"


class OrderItem(Base):
    __tablename__ = "order_items"

    id: Mapped[int] = mapped_column(primary_key=True)
    order_id: Mapped[int] = mapped_column(
        ForeignKey("orders.id"),
        index=True,
    )
    item: Mapped[str] = mapped_column(String(255))
    quantity: Mapped[int] = mapped_column()
    unit_price: Mapped[Decimal] = mapped_column(Numeric(12, 2))
    order: Mapped["Order"] = relationship(back_populates="items")


class OrderStatusHistory(Base):
    __tablename__ = "order_status_history"

    id: Mapped[int] = mapped_column(primary_key=True)
    order_id: Mapped[int] = mapped_column(
        ForeignKey("orders.id"),
        index=True,
    )
    old_status: Mapped[str] = mapped_column(String(100))
    new_status: Mapped[str] = mapped_column(String(100))
    changed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    changed_by: Mapped[int] = mapped_column(
        ForeignKey("users.id"),
        index=True,
    )
    order: Mapped["Order"] = relationship(back_populates="status_history")
    user: Mapped["User"] = relationship()


## Return for our company
class Return(Base):
    __tablename__ = "returns"

    id: Mapped[int] = mapped_column(primary_key=True)
    return_id: Mapped[str] = mapped_column(
        String(100),
        unique=True,
        index=True,
    )
    order_id: Mapped[int] = mapped_column(
        ForeignKey("orders.id"),
        index=True,
    )
    reason: Mapped[str] = mapped_column(String(500))
    status: Mapped[str] = mapped_column(String(50))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    order: Mapped["Order"] = relationship(back_populates="returns")

    def __repr__(self) -> str:
        return f"Return(id={self.id!r}, return={self.return_id!r}, order={self.order_id!r}, reason={self.reason!r}, status={self.status!r}, created-at={self.created_at!r}, updated-at={self.updated_at!r})"


class Payment(Base):
    __tablename__ = "payments"

    id: Mapped[int] = mapped_column(primary_key=True)
    payment_id: Mapped[str] = mapped_column(
        String(100),
        unique=True,
        index=True,
    )
    order_id: Mapped[int] = mapped_column(
        ForeignKey("orders.id"),
        index=True,
    )
    customer_id: Mapped[int] = mapped_column(ForeignKey("customers.id"), index=True)
    amount: Mapped[Decimal] = mapped_column(Numeric(12, 2))
    status: Mapped[str] = mapped_column(String(50))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    order: Mapped["Order"] = relationship(back_populates="payments")

    customer: Mapped["Customer"] = relationship(back_populates="payments")

    refunds: Mapped[list["Refund"]] = relationship(back_populates="payment")

    def __repr__(self) -> str:
        return f"Payment(id={self.id!r}, payment={self.payment_id!r}, order={self.order_id!r}, customer={self.customer_id!r}, amount={self.amount!r}, status={self.status!r}, created-at={self.created_at!r}, updated-at={self.updated_at!r})"


# Refund of the money on an order
class Refund(Base):
    __tablename__ = "refunds"

    id: Mapped[int] = mapped_column(primary_key=True)
    refund_id: Mapped[str] = mapped_column(
        String(100),
        unique=True,
        index=True,
    )

    order_id: Mapped[int] = mapped_column(
        ForeignKey("orders.id"),
        index=True,
    )
    payment_id: Mapped[int] = mapped_column(
        ForeignKey("payments.id"),
        index=True,
    )
    amount: Mapped[Decimal] = mapped_column(Numeric(12, 2))
    status: Mapped[str] = mapped_column(String(50))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    order: Mapped["Order"] = relationship(back_populates="refunds")

    payment: Mapped["Payment"] = relationship(back_populates="refunds")

    def __repr__(self) -> str:
        return f"Refund(id={self.id!r}, refund={self.refund_id!r},order={self.order_id!r}, payment={self.payment_id!r}, amount={self.amount!r}, status={self.status!r}, created-at={self.created_at!r}, updated-at={self.updated_at!r})"


class Case(Base):
    __tablename__ = "cases"

    id: Mapped[int] = mapped_column(primary_key=True)

    assigned_user_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id"),
        nullable=True,
    )

    assigned_user: Mapped["User | None"] = relationship(back_populates="cases")


class AgentAction(Base):
    __tablename__ = "agent_actions"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int | None] = mapped_column(  # the one who initiated the act
        ForeignKey("users.id"),
        nullable=True,
    )
    action_type: Mapped[str] = mapped_column(String(100))  # type of action
    entity_type: Mapped[str] = mapped_column(String(100))
    entity_id: Mapped[str] = mapped_column(String(100))
    description: Mapped[str] = mapped_column(String(2000))
    status: Mapped[str] = mapped_column(String(50))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )


## Classes for the knowledge base of the company(for rag)
class DocumentModel(Base):
    __tablename__ = "document_models"

    id: Mapped[int] = mapped_column(primary_key=True)
    title: Mapped[str] = mapped_column(String(255))
    category: Mapped[str] = mapped_column(String(1000)) ## Where the document belongs to(say, returns, payments, etc)
    department: Mapped[str] = mapped_column(String(1000)) ## Which department the document belongs to(say, customer support, finance, etc)
    current_version_id: Mapped[int] = mapped_column(ForeignKey("document_versions.id"), index=True) # The ID of the current version of the document
    role: Mapped[list[str]]  = mapped_column(String(1000))  ## The roles that can access this document. Multipe roles can be specified, separated by commas, and all roles can be specified by using "all"


class DocumentVersion(Base):
    __tablename__ = "document_versions"

    id: Mapped[int] = mapped_column(primary_key=True)
    document_id: Mapped[int] = mapped_column(ForeignKey("document_models.id"), index=True)
    version_number: Mapped[int] = mapped_column()
    content_hash: Mapped[str] = mapped_column(String(10000)) # This is used to check if the content has changed
    status: Mapped [DocumentStatus] = mapped_column(String(50), default=DocumentStatus.PROCESSING) # checking for the current status of the document version
    filename: Mapped[str] = mapped_column(String(1000)) # The name of the file that was uploaded
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )

class Chunk(Base):
    __tablename__ = "chunks"

    id: Mapped[int] = mapped_column(primary_key=True)
    document_version_id: Mapped[int] = mapped_column(ForeignKey("document_versions.id"), index=True)
    chunk_index: Mapped[int] = mapped_column() # helpful to identify/keep the order of the chunks in the document version
    content: Mapped[str] = mapped_column(String(10000)) # The content of the chunk
    content_hash: Mapped[str] = mapped_column(String(10000)) # This is used to check if the content has changed
    embedding: Mapped[list[float]] = mapped_column(VECTOR(1024)) # The embedding of the chunk
    chunk_metadata:Mapped[dict[str, Any]] = mapped_column(JSONB)# We get them from the pipeline, and store them in the database for future use
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )